package com.sunkitto.news.core.model.settings

import android.os.Parcelable
import androidx.annotation.StringRes
import com.sunkitto.news.core.model.R
import kotlinx.parcelize.Parcelize

@Parcelize
enum class TopHeadlinesCountry(
    @StringRes val nameId: Int,
    val isoCode: String,
) : Parcelable {
    ARGENTINA(R.string.argentina, "ar"),
    AUSTRALIA(R.string.australia, "au"),
    AUSTRIA(R.string.austria, "at"),
    BELGIUM(R.string.belgium, "be"),
    BRAZIL(R.string.brazil, "br"),
    BULGARIA(R.string.bulgaria, "bg"),
    CANADA(R.string.canada, "ca"),
    CHINA(R.string.china, "cn"),
    COLOMBIA(R.string.colombia, "co"),
    CUBA(R.string.cuba, "cu"),
    CZECHIA(R.string.czechia, "cz"),
    EGYPT(R.string.egypt, "eg"),
    FRANCE(R.string.france, "fr"),
    GERMANY(R.string.germany, "de"),
    GREECE(R.string.greece, "gr"),
    HONG_KONG(R.string.hong_kong, "hk"),
    HUNGARY(R.string.hungary, "hu"),
    INDIA(R.string.india, "in"),
    INDONESIA(R.string.indonesia, "id"),
    IRELAND(R.string.ireland, "ie"),
    ISRAEL(R.string.israel, "il"),
    ITALY(R.string.italy, "it"),
    JAPAN(R.string.japan, "jp"),
    KOREA(R.string.korea, "kr"),
    LATVIA(R.string.latvia, "lv"),
    LITHUANIA(R.string.lithuania, "lt"),
    MALAYSIA(R.string.malaysia, "my"),
    MEXICO(R.string.mexico, "mx"),
    MOROCCO(R.string.morocco, "ma"),
    NEW_ZEALAND(R.string.new_zealand, "nz"),
    NIGERIA(R.string.nigeria, "ng"),
    NORWAY(R.string.norway, "no"),
    PHILIPPINES(R.string.philippines, "ph"),
    POLAND(R.string.poland, "pl"),
    PORTUGAL(R.string.portugal, "pt"),
    ROMANIA(R.string.romania, "ro"),
    SAUDI_ARABIA(R.string.saudi_arabia, "sa"),
    SERBIA(R.string.serbia, "rs"),
    SINGAPORE(R.string.singapore, "sg"),
    SLOVAKIA(R.string.slovakia, "sk"),
    SLOVENIA(R.string.slovenia, "sl"),
    SOUTH_AFRICA(R.string.south_africa, "za"),
    SWEDEN(R.string.sweden, "se"),
    SWITZERLAND(R.string.switzerland, "ch"),
    TAIWAN(R.string.taiwan, "tw"),
    THAILAND(R.string.thailand, "th"),
    TURKEY(R.string.turkey, "tr"),
    UKRAINE(R.string.ukraine, "ua"),
    UNITED_ARAB_EMIRATES(R.string.united_arab_emirates, "ae"),
    UNITED_KINGDOM(R.string.united_kingdom, "gb"),
    USA(R.string.usa, "us"),
    VENEZUELA(R.string.venezuela, "ve"),
}